const 
ADD_TODO = 'ADD_TODO',
DELETE_TODO = 'DELETE_TODO',
SHOW_COMPLETED = 'SHOW_COMPLETED',
SHOW_IN_PROGRESS = 'SHOW_IN_PROGRESS',
MARK_COMPLETED = 'MARK_COMPLETED';
module.exports = {
   ADD_TODO,
   DELETE_TODO,
   SHOW_COMPLETED,
   SHOW_IN_PROGRESS,
   MARK_COMPLETED
}
