const CREATE_RECIPE = 'CREATE_RECIPE',
   EDIT_RECIPE = 'EDIT_RECIPE',
   GET_INDEX_OF_RECIPE_TO_EDIT = 'GET_INDEX_OF_RECIPE_TO_EDIT',
   REMOVE_RECIPE = 'REMOVE_RECIPE'
module.exports = {
   CREATE_RECIPE,
   REMOVE_RECIPE,
   EDIT_RECIPE,
   GET_INDEX_OF_RECIPE_TO_EDIT
}
