const
   ADD_TODO = 'ADD_TODO',
   DELETE_TODO = 'DELETE_TODO',
   TOGGLE_TODO = 'TOGGLE_TODO',
   SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
module.exports = {
   ADD_TODO,
   DELETE_TODO,
   TOGGLE_TODO,
   SET_VISIBILITY_FILTER
}